### ISSUE TITLE
Technical reproducibility

### ISSUE THREAD

**Issue by RemNil** [agbarnett/intervals#1]
Could you please kindly share the following files or explain how to produce them?
(1) meta.CI.RData, meta.CI.2.RData, journal.meta.RData, journal.meta.ii.RData, meta.numbers.RData,
(2) 0_find_abstracts_pubmed_numbers.R, 0_wikipedia_medicine.R, from1_data_from_Georgescu_Wren.R
Thank you very much!

**Comment by agbarnett** [comment]
I've uploaded those files except journal.meta.RData, journal.meta.ii.RData, which are here: https://github.com/agbarnett/decimal.places.
